# Generated by Django 6.0.1 on 2026-08-02 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('gameweek_points', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'League entries',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=8)),
                ('strength', models.PositiveSmallIntegerField(default=3)),
                ('badge', models.CharField(default='⚽', max_length=4)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3)),
                ('price', models.DecimalField(decimal_places=1, max_digits=4)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('selected_by_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fantasy.team')),
            ],
            options={
                'ordering': ['-total_points', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff', models.DateTimeField()),
                ('gameweek', models.PositiveSmallIntegerField(default=1)),
                ('difficulty', models.PositiveSmallIntegerField(default=3)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='fantasy.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='fantasy.team')),
            ],
            options={
                'ordering': ['kickoff'],
            },
        ),
    ]
