# Generated by Django 6.0.7 on 2026-08-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_player_assists_player_clean_sheets_player_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='fpl_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fpl_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='fpl_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
