# Generated by Django 6.0.7 on 2026-08-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_fixture_fpl_id_player_fpl_id_team_fpl_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Shown in the sidebar/brand mark across the site and admin. Square-ish images work best.', null=True, upload_to='branding/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Branding',
                'verbose_name_plural': 'Site Branding',
            },
        ),
    ]
