# Generated by Django 6.0.7 on 2026-08-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptainGameweekScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.PositiveIntegerField()),
                ('manager_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('gameweek', models.PositiveSmallIntegerField()),
                ('captain_name', models.CharField(blank=True, max_length=120)),
                ('captain_points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Captain gameweek score',
                'verbose_name_plural': 'Captain gameweek scores',
                'ordering': ['gameweek'],
                'unique_together': {('entry_id', 'gameweek')},
            },
        ),
    ]
