# Generated by Django 6.0.7 on 2026-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0005_captaingameweekscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='captaingameweekscore',
            name='gameweek_points',
            field=models.IntegerField(default=0),
        ),
    ]
