# Generated by Django 6.0.7 on 2026-08-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0006_captaingameweekscore_gameweek_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='captaingameweekscore',
            name='event_transfers_cost',
            field=models.PositiveSmallIntegerField(default=0, help_text='Points deducted for transfer hits taken this gameweek (e.g. 2 extra transfers = 4).'),
        ),
    ]
