# Generated by Django 6.0.7 on 2026-08-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0007_captaingameweekscore_event_transfers_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('captain_mode', 'Captain Mode'), ('classic_league', 'Classic League'), ('gameweek_winners', 'Gameweek Winners'), ('manager_of_the_month', 'Manager of the Month')], max_length=32, unique=True)),
                ('image', models.ImageField(blank=True, help_text="Shown in the advertisement half of this page's banner. Leave blank to show no ad. Landscape images work best.", null=True, upload_to='advertisements/')),
                ('link_url', models.URLField(blank=True, help_text='Optional - clicking the ad opens this link in a new tab.')),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility text for the ad image.', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Advertisement',
                'verbose_name_plural': 'Page Advertisements',
                'ordering': ['page'],
            },
        ),
    ]
