# Generated by Django 6.0.7 on 2026-08-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0009_seed_page_advertisements'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageadvertisement',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional short text shown to the right of the ad image (e.g. a tagline or short description).', max_length=200),
        ),
        migrations.AddField(
            model_name='pageadvertisement',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Optional - shows a small Facebook icon linking here.'),
        ),
        migrations.AddField(
            model_name='pageadvertisement',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Optional - shows a small Instagram icon linking here.'),
        ),
        migrations.AlterField(
            model_name='pageadvertisement',
            name='link_url',
            field=models.URLField(blank=True, help_text='Optional - clicking the ad image opens this link in a new tab.'),
        ),
    ]
