# Generated by Django 6.0.7 on 2026-08-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0010_pageadvertisement_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='captain_leaderboard_note',
            field=models.TextField(blank=True, default="<strong>How this is chosen:</strong> for every finished gameweek this season, each manager's captain earns their points multiplied by the captain multiplier (x2 normally, x3 with Triple Captain), added up across the whole season. The currently in-progress gameweek (if any) is fetched live and added on top. Ranked highest total first.", help_text='Shown under "Captain Points Leaderboard" on the Captain Mode page. Basic HTML (e.g. <strong>, <em>, <ul><li>) is allowed.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='captain_recommendation_note',
            field=models.TextField(blank=True, default='<strong>How the recommendation is chosen:</strong> every player in your squad gets a weighted captain score built from form, points per game, ICT index, goals, assists, clean sheets (extra weight for defenders/keepers), selection %, and minutes played, with a bonus for attacking positions.\n<ul>\n<li>The score is then scaled down for injury/rotation doubt &mdash; a player flagged as 50% likely to play has their score halved.</li>\n<li>Highest score becomes the <strong>Recommended Captain</strong>, second-highest becomes the <strong>Vice Captain</strong>.</li>\n</ul>', help_text='Shown on the Captain Mode page once a personal squad is loaded, explaining the recommendation. Basic HTML (e.g. <strong>, <em>, <ul><li>) is allowed.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='monthly_winner_note',
            field=models.TextField(blank=True, default="<strong>How the winner is chosen:</strong> for every gameweek whose deadline falls in the selected month, we add up each manager's gameweek points minus any transfer hit cost taken that gameweek: <strong>&Sigma; (GW points &minus; transfer hits)</strong>. Finished gameweeks are read from stored results; the current in-progress gameweek (if it falls in the selected month) is added live. Highest total for the month wins.", help_text='Shown under the month picker on the Manager of the Month page. Basic HTML (e.g. <strong>, <em>, <ul><li>) is allowed.'),
        ),
    ]
