# Generated by Django 6.0.7 on 2026-08-19 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0011_sitesettings_captain_leaderboard_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "FPL Bhaktapur S8" or "2025/26".', max_length=100, unique=True)),
                ('league_name', models.CharField(blank=True, max_length=150)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons (archive)',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonMonthlyWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_label', models.CharField(help_text='e.g. "August 2026".', max_length=20)),
                ('manager_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_winners', to='fantasy.season')),
            ],
            options={
                'ordering': ['season', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeasonCaptainStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('manager_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('captain_points', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_standings', to='fantasy.season')),
            ],
            options={
                'ordering': ['season', 'rank'],
                'unique_together': {('season', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='SeasonGameweekWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.PositiveSmallIntegerField()),
                ('manager_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameweek_winners', to='fantasy.season')),
            ],
            options={
                'ordering': ['season', 'gameweek'],
                'unique_together': {('season', 'gameweek')},
            },
        ),
        migrations.CreateModel(
            name='SeasonStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('manager_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='fantasy.season')),
            ],
            options={
                'ordering': ['season', 'rank'],
                'unique_together': {('season', 'rank')},
            },
        ),
    ]
