# Generated by Django 6.0.7 on 2026-08-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0012_season_seasonmonthlywinner_seasoncaptainstanding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
