# Generated by Django 6.0.7 on 2026-08-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0013_alter_player_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueentry',
            name='rank',
            field=models.PositiveIntegerField(),
        ),
    ]
