# Generated by Django 6.0.7 on 2026-09-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0014_alter_leagueentry_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_description',
            field=models.TextField(default='FPL Bhaktapur brings our Fantasy Premier League community together. Follow league standings, gameweek winners, monthly awards, and captain performances throughout the season.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_history',
            field=models.TextField(blank=True, default='Sample history: What began as a friendly competition grew into a shared season of football, rivalries, and memorable gameweeks. Replace this sample with the real story of FPL Bhaktapur.', help_text='Tell the story of the league, including its founding and memorable seasons. Plain text.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, default='Sample address — add your public contact location'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='hello@example.com', help_text='Sample email: replace before publishing.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='Sample phone — add your number', max_length=50),
        ),
    ]
